# Generated by Django 5.1.4 on 2025-02-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navolga_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navolga_main.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navolga_main.product')),
            ],
        ),
    ]
