# Generated by Django 5.1.4 on 2025-01-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snipet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
